# Generated by Django 5.0.4 on 2024-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_treasuryuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='treasuryuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=0, max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=0, max_length=30, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
